server:
  port: 8762

spring:
  application:
    name: eureka

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://39.106.71.119:8761/eureka/,http://39.106.71.119:8763/eureka/
    fetch-registry: false
#  server:
#    enable-self-preservation: false

