server:
  port: 8762

spring:
  application:
    name: merry

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://39.106.71.119:8761/wooden/,http://39.106.71.119:8763/sunny/
  server:
    enable-self-preservation: false
